name: Deploy poc java lambda

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Build
        run: ./gradlew build --no-daemon