name: Deploy poc java lambda

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
        cache: 'gradle'
    - run: ./gradlew build --no-daemon