name: Deploy poc java lambda

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: https://test.com
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            build/distributions/hello.zip
            serverless.yml

  Deploy Prod:
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: https://test.com
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - shell: bash
        run: ls
      - name: Serverless Deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  Deploy Hml:
    needs: Build
    runs-on: ubtuntu-latest
    environment:
      name: Hml
      url: https://test.com
    steps:
      - Name: Deploy Hml
        run: echo "Deploy Html"