name: Deploy poc java lambda

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://test.com
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://test.com
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Install Plugin and Deploy
        uses: serverless/github-action@v2
        with:
          args: -c "serverless plugin install --name serverless-iam-roles-per-function && serverless deploy --stage production"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}